version: '3'
services:
  server:
    build:
      context: ./server/
    command: npm start
    volumes:
      - ./server/:/usr/app
      - /usr/app/node_modules
    ports:
      - "9000:9000"
    # env_file: ./server/.env # TODO - uncomment this to auto-load your .env file!
    environment:
      - API_URL=http://localhost:9000/api
      - CLIENT_URL=http://localhost:3000
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  client:
    build:
      context: ./client/piek/
    command: npm start
    volumes:
      - ./client/piek/:/app/client
      - /app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"