version: '3'


services:
  web:
    build: .
    ports:
      - "9000:9000"
    restart: always
    # env_file: ./server/.env # TODO - uncomment this to auto-load your .env file!
    environment:
      - CLIENT_URL=http://localhost:9000
      NODE_ENV: production
      PORT: 9000