version: '3'
services:
  server:
    build:
      context: ./server/
    command: npm start
    volumes:
      - ./server/:/usr/app
      - /usr/app/node_modules
    ports:
      - "9000:9000"
    env_file: server/.env

  client:
    build:
      context: ./client/piek/
    command: npm start
    volumes:
      - ./client/piek/:/app/client
      - /app/node_modules
    environment: 
      - REACT_APP_API_URL=http://localhost:9000/api
      - REACT_APP_HASURA_WS=ws://45.10.110.58:8080/v1/graphql 
    depends_on:
      - server
    ports:
      - "3000:3000"