query GetReclamationOrders {
  erp_Orders(where: { OrderStatusID: { _in: [10, 11, 12] } }) {
    AwaitingDispatch
    NeedAttention
    OrderID
    Entity
    City
    OrderStatusID
    OrderItems(order_by: { OrderItemID: asc }) {
      OrderItemID
      Name
    }
  }
}

mutation UpdateOrderStatus($OrderID: Int!, $OrderStatusID: Int!) {
  update_erp_Orders_by_pk(
    pk_columns: { OrderID: $OrderID }
    _set: { OrderStatusID: $OrderStatusID }
  ) {
    OrderID
    OrderStatusID
  }
}
