###

POST http://localhost:9000/api/login
Content-Type: application/json

{
    "email": "l@gmail.com",
    "password": "l"
}

###

POST http://localhost:9000/api/logout
Content-Type: application/json

{
    "email": "loseev5@gmail.com",
    "password": "loseev02"

}

### 

GET http://localhost:9000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOjE1LCJGaXJzdE5hbWUiOiLQmtGC0L4iLCJMYXN0TmFtZSI6bnVsbCwiRW1haWwiOiJsb3NlZXY1QGdtYWlsLmNvbSIsIlBhc3N3b3JkIjoibG9zZWV2MDIiLCJSZWZyZXNoVG9rZW4iOiJleUpoYkdjaU9pSklVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKVmMyVnlTVVFpT2pFMUxDSkdhWEp6ZEU1aGJXVWlPaUxRbXRHQzBMNGlMQ0pNWVhOMFRtRnRaU0k2Ym5Wc2JDd2lSVzFoYVd3aU9pSnNiM05sWlhZMVFHZHRZV2xzTG1OdmJTSXNJbEJoYzNOM2IzSmtJam9pYkc5elpXVjJNRElpTENKU1pXWnlaWE5vVkc5clpXNGlPaUlpTENKQlkyTmxjM05NWlhabGJDSTZiblZzYkN3aWFXRjBJam94TmpJME16STBPVFExTENKbGVIQWlPakUyTWpZNU1UWTVORFY5LkJLN2o3UTNpUk5tWWxUQkFNZFNsbldPUkxRUEp2UHlkaUdUYmJfc3VBb0UiLCJBY2Nlc3NMZXZlbCI6bnVsbCwiaWF0IjoxNjI0NjYwMzYxLCJleHAiOjE2MjQ2NjIxNjF9.7BdY8v4_sWN_1yDB7APZ9H8gfA84h34K7uLXZSjE8Zo

{
    "email": "loseev5@gmail.com",
    "password": "loseev02"

}