name: Deployment

on:
  workflow_dispatch

jobs:
  deploy:
    # Defines the type of runner the job runs on
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@master
    - name: Generate the artifacts
      uses: skx/github-action-build@master
    - name: Upload the artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'example-*'
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        key: ${{ secrets.SSH_HEXCORE_KEY }}
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: 22
        script: |
          cd ~/erp/
          git pull
          docker-compose up -d --force-recreate --build
          docker image rm -f $(docker images -f dangling=true -q)
