name: Deployment

on:
  workflow_dispatch

jobs:
  deploy:
    # Defines the type of runner the job runs on
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        key: ${{ secrets.SSH_HEXCORE_KEY }}
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: 22
        script: |
          cd ~/erp/
          git pull
          docker-compose up -d --force-recreate --build
          docker image rm -f $(docker images -f dangling=true -q)
