name: Deploy from main

on:
  workflow_dispatch

jobs:
  deploy:
    # Defines the type of runner the job runs on
    runs-on: ubuntu-latest

    steps:
    - name: Create annotation for build error
      run: echo "${{ env.SSH_HEXCORE_KEY }}"
    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ env.SSH_HEXCORE_KEY }}
        ARGS: "-v --stats --progress"
        REMOTE_HOST: ${{ env.SSH_HOST }}
        REMOTE_USER: ${{ env.SSH_USER }}
