name: Deploy to production

on: workflow_dispatch

jobs:
  deploy:
    # Defines the type of runner the job runs on
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_HEXCORE_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: 22
          script: |
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.CR_TOKEN }}
            docker pull ghcr.io/spooky-finn/piekerp:latest
            docker stop piekerp
            docker rm piekerp
            docker run -d --name piekerp -p 9000:9000 --env-file ~/erp/.env ghcr.io/spooky-finn/piekerp:latest
